apiVersion: v1
kind: Pod
metadata:
  #Adjust PAWPRINT HERE
  name: askvy-ue
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: dockerconfigjson-github-com
  containers:
    #Adjust PAWPRINT HERE
    - name: askvy-ue
      image: ghcr.io/legibleguy/mizsim:ue5.3-u20.04
      command: ["/bin/bash", "-c"]
      args:
        - |
          cd ../
          git clone https://github.com/legibleguy/airsim-blocks.git
          mv airsim-blocks Blocks
          cd HeadlessUnrealFlightAgent
          git pull
          yq eval '.unreal.project_path = "/home/ue4/Blocks"' docker-config.yml -i
          ./run.sh docker-config.yml
          sleep infinity
      resources:
        limits:
          memory: 8Gi
          cpu: 4
          nvidia.com/gpu: 1 # Request 1 GPU
        requests:
          memory: 8Gi
          cpu: 4
          nvidia.com/gpu: 1 # Request 1 GPU
      volumeMounts:
        - mountPath: /workspace/unreal
          name: ue-workspace
  volumes:
    - name: ue-workspace
      persistentVolumeClaim:
        claimName: askvyue-workspace
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.present # Check if GPU is present on the node
                operator: Exists
            matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - NVIDIA-GeForce-RTX-3090
                  - NVIDIA-TITAN-RTX
                  - NVIDIA-RTX-A5000
                  - Quadro-RTX-6000
                  - NVIDIA-A10