apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: askvyue-workspace
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi